package com.localmind.app.domain.model

data class ModelCatalogItem(
    val id: String,
    val name: String,
    val repoId: String,
    val author: String,
    val lastModified: String? = null,
    val description: String,
    val parameterCount: String,
    val sizeGb: Double,
    val quantization: String,
    val ggufFileName: String,
    val downloadUrl: String,
    val category: ModelCategory,
    val minRamGb: Int,
    val downloads: Int = 0,
    val likes: Int = 0,
    val tags: List<String> = emptyList(),
    val isVision: Boolean = false,
    val requiresToken: Boolean = false,
    val isDownloaded: Boolean = false,
    val isDownloading: Boolean = false,
    val downloadProgress: Float = 0f,
    val templateId: String = "chatml_default",
    val stopTokens: List<String> = emptyList(),
    val recommendedTemperature: Float = 0.7f,
    val recommendedTopP: Float = 0.9f,
    val recommendedTopK: Int = 40,
    val recommendedRepeatPenalty: Float = 1.1f,
    val recommendedSystemPrompt: String? = null,
    val compatibilityWarning: String? = null,
    val isCompatible: Boolean = true,
    val compatibilityReason: String? = null,
    val compatibilityState: ModelCompatibilityState = ModelCompatibilityState.COMPATIBLE,
    val compatibilityFixTips: List<String> = emptyList(),
    val memoryTier: ModelMemoryTier = ModelMemoryTier.GOOD,
    val runTarget: ModelRunTarget = ModelRunTarget.LOCAL,
    val variants: List<ModelVariant> = emptyList(),
    val selectedVariantFilename: String? = null
)
